// Lot Walk capture session: camera/photo controls must work even if IndexedDB is slow or unavailable.
(function(){
  const DB_NAME='lot-walk-session-v1',STORE='captures';
  const session={id:'',db:null,dbReady:false,mem:new Map(),queue:[],processing:false,counts:{saved:0,processed:0,unresolved:0,error:0,waiting:0}};

  function makeId(){const a=new Uint32Array(3);crypto.getRandomValues(a);return `cap-${Date.now().toString(36)}-${[...a].map(x=>x.toString(36)).join('')}`;}
  function currentSessionId(){let id=sessionStorage.getItem('lotWalkSessionId');if(!id){id=`walk-${new Date().toISOString().slice(0,10)}-${Math.random().toString(36).slice(2,8)}`;sessionStorage.setItem('lotWalkSessionId',id);}return id;}
  function dbOpen(){return new Promise((resolve,reject)=>{if(!window.indexedDB)return reject(Error('IndexedDB unavailable'));let done=false;const fail=e=>{if(done)return;done=true;reject(e instanceof Error?e:Error('Session database unavailable'));};const timer=setTimeout(()=>fail(Error('Session database timed out')),1800);let req;try{req=indexedDB.open(DB_NAME,1);}catch(e){clearTimeout(timer);return fail(e);}req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains(STORE)){const s=db.createObjectStore(STORE,{keyPath:'id'});s.createIndex('sessionId','sessionId');s.createIndex('status','status');}};req.onsuccess=()=>{if(done){try{req.result.close()}catch{}return;}done=true;clearTimeout(timer);resolve(req.result);};req.onerror=()=>{clearTimeout(timer);fail(req.error||Error('Session database failed'));};});}
  function dbPut(rec){if(!session.dbReady||!session.db)return Promise.resolve(rec);return new Promise(resolve=>{try{const tx=session.db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(rec);tx.oncomplete=()=>resolve(rec);tx.onerror=()=>resolve(rec);}catch{resolve(rec);}});}
  async function put(rec){session.mem.set(rec.id,rec);await dbPut(rec);return rec;}
  async function get(id){if(session.mem.has(id))return session.mem.get(id);if(!session.dbReady||!session.db)return null;return new Promise(resolve=>{try{const tx=session.db.transaction(STORE,'readonly'),req=tx.objectStore(STORE).get(id);req.onsuccess=()=>{if(req.result)session.mem.set(id,req.result);resolve(req.result||null);};req.onerror=()=>resolve(null);}catch{resolve(null);}});}
  async function allForSession(){const map=new Map([...session.mem].filter(([,r])=>r.sessionId===session.id));if(session.dbReady&&session.db){await new Promise(resolve=>{try{const tx=session.db.transaction(STORE,'readonly'),req=tx.objectStore(STORE).index('sessionId').getAll(session.id);req.onsuccess=()=>{for(const r of req.result||[])if(!map.has(r.id))map.set(r.id,r);resolve();};req.onerror=()=>resolve();}catch{resolve();}});}return [...map.values()];}
  function canvasFrom(source,max=1600){const sw=source.videoWidth||source.naturalWidth||source.width,sh=source.videoHeight||source.naturalHeight||source.height;if(!sw||!sh)throw Error('Camera frame not ready');const scale=Math.min(1,max/Math.max(sw,sh)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(sw*scale));c.height=Math.max(1,Math.round(sh*scale));c.getContext('2d').drawImage(source,0,0,c.width,c.height);return c;}
  function jpeg(c){return new Promise((resolve,reject)=>c.toBlob(b=>b?resolve(b):reject(Error('Could not save photo')),'image/jpeg',.84));}
  function imageFromBlob(blob){return new Promise((resolve,reject)=>{const img=new Image(),url=URL.createObjectURL(blob);img.onload=()=>{URL.revokeObjectURL(url);resolve(img)};img.onerror=()=>{URL.revokeObjectURL(url);reject(Error('Saved photo could not be opened by this browser'))};img.src=url;});}
  function matchSummary(m){if(!m)return null;return{status:m.status||'',confidence:m.confidence||'',score:m.score||0,evidence:m.evidence||[],rows:(m.rows||[]).map(r=>({ro:r.ro||'',vin:r.vin||'',stock:r.stock||'',customer:r.customer||'',year:r.year||'',make:r.make||'',model:r.model||''}))};}

  function injectUI(){if($('captureSessionCard'))return;const area=$('scanAreaCard');if(!area)return;const card=document.createElement('div');card.id='captureSessionCard';card.className='card';card.innerHTML=`<div class="row"><b>Walk Session</b><span id="captureSummary" class="pill">0 photos</span></div><div id="captureStatus" class="status" style="margin-top:8px">Ready. Scan Now or Use Photos will save immediately.</div><div id="captureRecent" style="margin-top:8px"></div>`;area.insertAdjacentElement('afterend',card);}
  async function refresh(){const rows=(await allForSession()).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));session.counts.saved=rows.length;session.counts.processed=rows.filter(r=>['MATCH','UNRESOLVED'].includes(r.status)).length;session.counts.unresolved=rows.filter(r=>r.status==='UNRESOLVED').length;session.counts.error=rows.filter(r=>r.status==='ERROR').length;session.counts.waiting=rows.filter(r=>r.status==='WAITING FOR WOS').length;if($('captureSummary'))$('captureSummary').textContent=`${rows.length} photos · ${session.counts.unresolved} unresolved${session.counts.waiting?` · ${session.counts.waiting} waiting`:''}`;if($('captureRecent'))$('captureRecent').innerHTML=rows.slice(0,8).map(r=>`<div class="testrow"><b>${r.area}</b> · ${r.status}${r.name?` · ${escapeHtml(r.name)}`:''}${r.match?.rows?.length?` · RO ${r.match.rows.map(x=>x.ro).join('/')}`:''}<span class="muted"> · ${new Date(r.createdAt).toLocaleTimeString()}</span></div>`).join('');}

  async function saveBlob(blob,area,{queue=true,width=0,height=0,name=''}={}){if(!['SERVICE','SALES'].includes(area))throw Error('Choose Service Area or Sales Area first');const rec={id:makeId(),sessionId:session.id,createdAt:new Date().toISOString(),area,status:'SAVED',blob,width,height,name};await put(rec);await refresh();if(queue){session.queue.push(rec.id);setTimeout(processQueue,0);}return rec;}
  async function saveCapture(source,area,{queue=true}={}){const c=canvasFrom(source),blob=await jpeg(c),rec=await saveBlob(blob,area,{queue,width:c.width,height:c.height});if($('scanStatus'))$('scanStatus').textContent=`Photo saved · ${area} · move to next unit.`;if($('captureStatus'))$('captureStatus').textContent=`Saved camera photo to ${area}. Recognition is running in the background.`;if($('resultCard'))$('resultCard').classList.add('hidden');return rec;}

  async function processOne(id){let rec=await get(id);if(!rec||!rec.blob)return;if(!state.workOrders.length){rec.status='WAITING FOR WOS';await put(rec);await refresh();return;}rec.status='PROCESSING';await put(rec);await refresh();try{const img=await imageFromBlob(rec.blob),scan=await window.lotWalkScanSourceV10(img,{render:false}),m=scan?.match||matchOCR(scan?.text||'');rec.match=matchSummary(m);rec.status=m?.status==='MATCH'?'MATCH':'UNRESOLVED';rec.read=scan?.text||'';rec.processedAt=new Date().toISOString();await put(rec);if(window.lotWalkPairing?.submitCapture)await window.lotWalkPairing.submitCapture(rec);}catch(e){rec.status='ERROR';rec.error=e.message;rec.processedAt=new Date().toISOString();await put(rec);console.error('capture processing',e);}await refresh();}
  async function processQueue(){if(session.processing)return;session.processing=true;try{while(session.queue.length)await processOne(session.queue.shift());}finally{session.processing=false;}}
  async function resumeWaiting(){if(!state.workOrders.length)return;for(const r of await allForSession())if(['WAITING FOR WOS','SAVED'].includes(r.status)&&!session.queue.includes(r.id))session.queue.push(r.id);if(session.queue.length)setTimeout(processQueue,0);}
  async function receiveRemote(meta,blob){const existing=await get(meta.id),rec={...(existing||{}),...meta,sessionId:session.id,blob:blob||existing?.blob};await put(rec);await refresh();}

  async function scanNow(){if(!state.activeArea){$('scanStatus').textContent='Choose Service Area or Sales Area before scanning.';return;}if(!video.videoWidth||video.readyState<2){$('scanStatus').textContent='Camera is not ready yet. Tap Start Camera.';return;}const b=$('scanNow'),old=b.textContent;b.textContent='Saving…';b.disabled=true;try{await saveCapture(video,state.activeArea,{queue:true});}catch(e){$('scanStatus').textContent='Photo not saved: '+e.message;}finally{b.textContent=old;b.disabled=false;}}

  async function importPhotos(files){const list=[...files];if(!list.length)return;if(!state.activeArea){$('scanStatus').textContent='Choose Service Area or Sales Area before selecting photos.';if($('captureStatus'))$('captureStatus').textContent='Photos not imported: choose Service Area or Sales Area first.';return;}const status=$('scanStatus'),cap=$('captureStatus');status.textContent=`Selected ${list.length} photo${list.length===1?'':'s'} · saving now…`;if(cap)cap.textContent=`Selected ${list.length} photo${list.length===1?'':'s'} · saving now…`;const ids=[];let failed=0;for(const file of list){try{const rec=await saveBlob(file,state.activeArea,{queue:false,name:file.name||'phone photo'});ids.push(rec.id);}catch(e){failed++;console.error('photo import',e);}}for(const id of ids)session.queue.push(id);setTimeout(processQueue,0);const msg=`${ids.length} photo${ids.length===1?'':'s'} saved to ${state.activeArea}${failed?` · ${failed} failed`:''}.`;status.textContent=msg;if(cap)cap.textContent=msg;await refresh();}

  function bindControlsNow(){injectUI();const scan=$('scanNow');if(scan)scan.onclick=scanNow;const picker=$('photoFile');if(picker){picker.removeAttribute('capture');picker.multiple=true;picker.addEventListener('change',async e=>{const files=[...(e.target.files||[])];if(!files.length)return;try{await importPhotos(files);}catch(err){console.error('photo picker',err);if($('scanStatus'))$('scanStatus').textContent='Photo import failed: '+err.message;if($('captureStatus'))$('captureStatus').textContent='Photo import failed: '+err.message;}finally{e.target.value='';}});}}

  session.id=currentSessionId();
  bindControlsNow();
  window.lotWalkCaptureSession={saveCapture,saveBlob,importPhotos,processQueue,resumeWaiting,receiveRemote,all:allForSession,sessionId:()=>session.id,counts:()=>({...session.counts}),storage:()=>session.dbReady?'indexeddb+memory':'memory'};
  refresh();
  const priorSetRows=setRows;setRows=function(rows,label=''){priorSetRows(rows,label);setTimeout(resumeWaiting,0);};
  dbOpen().then(async db=>{session.db=db;session.dbReady=true;for(const r of session.mem.values())await dbPut(r);await refresh();if($('captureStatus')&&$('captureStatus').textContent==='Ready. Scan Now or Use Photos will save immediately.')$('captureStatus').textContent='Ready. Phone session storage is available.';}).catch(e=>{console.warn('Lot Walk using memory photo storage:',e.message);if($('captureStatus'))$('captureStatus').textContent='Ready. Photos will stay in this open phone session.';});
})();