import puppeteer from 'puppeteer-core';
import {execSync} from 'node:child_process';
import fs from 'node:fs';
const result={time:new Date().toISOString(),success:false,checks:{},output:null,error:null};let browser;
try{
 const chrome=execSync('which google-chrome || which chromium || which chromium-browser',{encoding:'utf8'}).trim().split('\n')[0];
 browser=await puppeteer.launch({headless:true,executablePath:chrome,args:['--no-sandbox','--disable-dev-shm-usage']});
 const page=await browser.newPage();page.setDefaultTimeout(240000);const errs=[];page.on('pageerror',e=>errs.push(e.message));page.on('console',m=>{if(m.type()==='error')errs.push(m.text())});
 await page.goto('http://127.0.0.1:8000/staging-r22.html',{waitUntil:'domcontentloaded'});
 await page.waitForFunction(()=>window.__urrTest?.analyzeData&&window.URR_R21_DOMAIN_TEST,{timeout:90000});
 const domain=await page.evaluate(()=>window.URR_R21_DOMAIN_TEST);result.checks.domain=`${domain.pass}/${domain.total}`;if(domain.pass!==domain.total)throw new Error('Domain benchmark failed');
 const math=await page.evaluate(()=>window.__urrTest.math());result.checks.math=math;if(math.a!==130||math.b!==65||math.c!==775||math.d!==80)throw new Error('Pricing regression '+JSON.stringify(math));
 const data=await page.evaluate(()=>{const c=document.createElement('canvas');c.width=1200;c.height=1680;const x=c.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,1200,1680);x.strokeStyle='#333';x.lineWidth=2;x.fillStyle='#111';x.font='bold 42px Arial';x.textAlign='center';x.fillText("Bish's RV Used",600,75);x.fillText('Recommended Repairs',600,125);x.textAlign='left';const hc=[60,234,376,517,660,806,954,1110],HT=176,HB=350;x.strokeRect(hc[0],HT,hc.at(-1)-hc[0],HB-HT);for(const v of hc){x.beginPath();x.moveTo(v,HT);x.lineTo(v,HB);x.stroke()}x.font='22px Arial';['Make','Model','Stock#','RO#','Date','Tech','Outfitter'].forEach((t,i)=>x.fillText(t,hc[i]+10,212));x.font='30px Arial';x.fillText('105779',535,300);const L=60,R=1110,TT=383,RH=60,rows=16,DE=486,TE=660,FE=870,AE=930;x.strokeRect(L,TT,R-L,RH*(rows+1));for(let i=0;i<=rows+1;i++){const y=TT+i*RH;x.beginPath();x.moveTo(L,y);x.lineTo(R,y);x.stroke()}for(const v of [105,DE,TE,FE,AE]){x.beginPath();x.moveTo(v,TT);x.lineTo(v,TT+RH*(rows+1));x.stroke()}x.font='bold 21px Arial';x.fillText('Problem Found/Repair Needed',125,420);x.fillText('Total Cost',680,411);x.fillText('of Repair',690,435);x.fillText('Fix',885,420);x.fillText('As Is',940,420);x.fillText('SM/GM',1000,420);const jobs=[['ROOF SPOT SEAL','$60','2 HR','$460'],['ODS EXTERIOR TRIM RESEAL','$30','.5 HR','$130'],['LP DETECTOR OUT OF DATE REPLACE','$65','.5 HR','$165'],['WBP','$80','2.60 HR','$600']];x.font='31px cursive';jobs.forEach((j,i)=>{const y=TT+RH*(i+1)+42;x.fillStyle='#202020';x.fillText(j[0],125,y);x.fillStyle='#b31919';x.fillText(j[1],505,y);x.fillText(j[2],570,y);x.fillStyle='#3420a8';x.fillText(j[3],680,y)});return c.toDataURL('image/png')});
 const out=await page.evaluate(async d=>window.__urrTest.analyzeData(d,'quote'),data);result.output=out;result.checks.ro=out.ro;result.checks.jobCount=out.jobs?.length||0;const titles=(out.jobs||[]).map(j=>String(j.title||'').toLowerCase());result.checks.titles=titles;if(out.ro!=='105779')throw new Error('RO mismatch '+out.ro);if((out.jobs?.length||0)!==4)throw new Error('Expected exactly 4 jobs, got '+(out.jobs?.length||0));for(const w of ['roof','exterior','detector','wbp'])if(!titles.some(t=>t.includes(w)))throw new Error('Missing '+w+' in '+JSON.stringify(titles));if(errs.filter(e=>!e.includes('favicon')).length)throw new Error('Browser errors '+errs.join(' | '));result.success=true;
}catch(e){result.error=String(e?.stack||e)}finally{if(browser)await browser.close();fs.mkdirSync('validation',{recursive:true});fs.writeFileSync('validation/r22-fullsheet-result.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2))}if(!result.success)process.exitCode=1;
